#define TAM_ALUNO 10000
#define TAM_PROFESSOR 1000
#define TAM_DISICPLINA 100

#define ERRO_SEXO_ALUNO -1
#define ALUNO_SUCESSO -2
#define ALUNO_NAO_ENCONTRADO -3
#define SUCESSO_EXCLUSAO_ALUNO -4
#define ALUNO_ATUALIZADO -5
#define DATA_ALUNO_SUCESSO -6
#define DATA_ALUNO_ERRO -7

#define ERRO_SEXO_PROFESSOR -8
#define PROFESSOR_SUCESSO -9
#define PROFESSOR_NAO_ENCONTRADO -10
#define SUCESSO_EXCLUSAO_PROFESSOR -11
#define PROFESSOR_ATUALIZADO -12
#define DATA_PROFESSOR_SUCESSO -13
#define DATA_PROFESSOR_ERRO -14

#define DISCIPLINA_SUCESSO -15
#define DISCIPLINA_NAO_ENCONTRADA -16
#define SUCESSO_EXCLUSAO_DICIPLINA -17
#define DISCIPLINA_ATUALIZADA_SUCESSO -18
